preflop_ranges = {
    "UTG": {
        "66", "77", "88", "99", "TT", "JJ", "QQ", "KK", "AA",
        "A3s", "A4s", "A5s", "A6s", "A7s", "A8s", "A9s", "ATs", "AJs", "AQs", "AKs",
        "ATo", "AJo", "AQo", "AKo",
        "K8s", "K9s", "KTs", "KJs", "KQs",
        "KJo", "KQo", 
        "Q9s", "QTs", "QJs",
        "J9s", "JTs",
        "T9s"
    },
    "MP": {
        "66", "77", "88", "99", "TT", "JJ", "QQ", "KK", "AA",
        "A2s", "A3s", "A4s", "A5s", "A6s", "A7s", "A8s", "A9s", "ATs", "AJs", "AQs", "AKs",
        "ATo", "AJo", "AQo", "AKo",
        "K5s", "K6s", "K7s", "K8s", "K9s", "KTs", "KJs", "KQs",
        "KTo", "KJo", "KQo",
        "Q8s", "Q9s", "QTs", "QJs",
        "QTo", "QJo",
        "J9s", "JTs",
        "T9s",
        "98s"
    },
    "CO": {
        "22", "33", "44", "55", "66", "77", "88", "99", "TT", "JJ", "QQ", "KK", "AA",
        "A2s", "A3s", "A4s", "A5s", "A6s", "A7s", "A8s", "A9s", "ATs", "AJs", "AQs", "AKs",
        "A8o", "A9o", "ATo", "AJo", "AQo", "AKo",
        "K3s", "K4s", "K5s", "K6s", "K7s", "K8s", "K9s", "KTs", "KJs", "KQs",
        "KTo", "KJo", "KQo", 
        "Q5s", "Q6s", "Q7s", "Q8s", "Q9s", "QTs", "QJs", 
        "QTo", "QJo",
        "J7s", "J8s", "J9s", "JTs",
        "JTo",
        "T7s", "T8s", "T9s",
        "97s", "98s",
        "87s",
        "76s",
        "65s"
    },
    "BTN": {
        "22", "33", "44", "55", "66", "77", "88", "99", "TT", "JJ", "QQ", "KK", "AA",
        "A2s", "A3s", "A4s", "A5s", "A6s", "A7s", "A8s", "A9s", "ATs", "AJs", "AQs", "AKs",
        "A4o", "A5o", "A6o", "A7o", "A8o", "A9o", "ATo", "AJo", "AQo", "AKo",
        "K2s", "K3s", "K4s", "K5s", "K6s", "K7s", "K8s", "K9s", "KTs", "KJs", "KQs",
        "K8o", "K9o", "KTo", "KJo", "KQo",
        "Q2s", "Q3s", "Q4s", "Q5s", "Q6s", "Q7s", "Q8s", "Q9s", "QTs", "QJs", 
        "Q9o", "QTo", "QJo",
        "J4s", "J5s", "J7s", "J8s", "J9s", "JTs", 
        "J9o", "JTo",
        "T6s", "T7s", "T8s", "T9s",
        "T8o","T9o",
        "96s", "97s", "98s",
        "98o",
        "85s", "86s", "87s",
        "75s", "76s", 
        "64s", "65s", 
        "54s"
    },
    "SB": {
        "22", "33", "44", "55", "66", "77", "88", "99", "TT", "JJ", "QQ", "KK", "AA",
        "A2s", "A3s", "A4s", "A5s", "A6s", "A7s", "A8s", "A9s", "ATs", "AJs", "AQs", "AKs",
        "A4o", "A5o", "A6o", "A7o", "A8o", "A9o", "ATo", "AJo", "AQo", "AKo",
        "K2s", "K3s", "K4s", "K5s", "K6s", "K7s", "K8s", "K9s", "KTs", "KJs", "KQs",
        "K8o", "K9o", "KTo", "KJo", "KQo",
        "Q2s", "Q3s", "Q4s", "Q5s", "Q6s", "Q7s", "Q8s", "Q9s", "QTs", "QJs", 
        "Q9o", "QTo", "QJo",
        "J4s", "J5s", "J7s", "J8s", "J9s", "JTs", 
        "J9o", "JTo",
        "T6s", "T7s", "T8s", "T9s",
        "T8o","T9o",
        "96s", "97s", "98s",
        "98o",
        "85s", "86s", "87s",
        "75s", "76s", 
        "64s", "65s", 
        "54s"
    },
    "BB": set()
}